package parameter

const KOMPONENTARIF_ID_TOTAL = 3
const KOMPONENTARIF_ID_AKOMODASI = 2               //pelayanan rs
const KOMPONENTARIF_ID_JASA_MEDIS = 1              //dokter
const KOMPONENTARIF_ID_JASA_PARAMEDIS = 52         //petugas
const KOMPONENTARIF_ID_BHP = 44                    //bhp
const KELOMPOKKOMPONENTARIF_ID_JASA_MEDIS = 1      //dokter
const KELOMPOKKOMPONENTARIF_ID_JASA_PARAMEDIS = 30 //petugas
const KELOMPOKKOMPONENTARIF_ID_JASA_RETRIBUSI = 2  //rs

const KELASPELAYANAN_ID_TANPAKELAS = 6

const RUANGAN_ID_LAB = 4 //taken
const RUANGAN_ID_RAD = 5 //taken

const INSTALASI_ID_RM = 1   //taken
const INSTALASI_ID_RJ = 2   //taken
const INSTALASI_ID_RD = 3   //taken
const INSTALASI_ID_RI = 4   //taken
const INSTALASI_ID_LAB = 46 //taken
const INSTALASI_ID_RAD = 47 //taken
const INSTALASI_ID_IBS = 5  //taken
const INSTALASI_ID_REHAB = 0
const INSTALASI_ID_FARMASI = 0
const INSTALASI_ID_GIZI = 0
const INSTALASI_ID_JZ = 0
const INSTALASI_ID_AMBULAN = 0
const INSTALASI_ID_KASIR = 0
const INSTALASI_ID_LOGISTIK = 0
const INSTALASI_ID_ICU = 0
const INSTALASI_ID_KEPEGAWAIAN = 0
const INSTALASI_ID_GUDANG_FARMASI = 0
const INSTALASI_ID_LAUNDRY = 0

const CARA_BAYAR_BPJS = 2
const CARA_BAYAR_BPJS_PBI = 2
const CARA_BAYAR_PRIBADI = 1

const PENJAMIN_ID_PRIBADI = 42
const PENJAMIN_ID_PEMERINTAH = 20

const CORPORATE_ID_PRIBADI = 99999

const CORP_BPJS = 1
const CORP_UMUM = 0

const KEWARGANEGARAAN_INDONESIA = "WNI"
const KEWARGANEGARAAN_ASING = "ASING"

const CARAMASUK_ID_RAJAL = 1
const CARAMASUK_ID_RANAP_LANGSUNG = 3
const CARAMASUK_ID_IGD = 2

const ZONA_WAKTU = "Asia/Jakarta"
